all: udp_client udp_server

udp_client: udp_client.c
	gcc -Wextra -Wall -pedantic -g -o client/client udp_client.c

udp_server: udp_server.c 
	gcc -Wextra -Wall -pedantic -g -o server/server udp_server.c